PROGRAM LAPLACE
    INTEGER, PARAMETER :: XSIZE=11,YSIZE=11
    REAL, DIMENSION(1:XSIZE,1:YSIZE) :: PHIOLD,PHINEW
    REAL :: MAXDELTA

    REAL, PARAMETER :: CONVERGENCE = 0.0001
    INTEGER :: ITERATIONS = 0

    INTEGER :: I,J

    PHINEW(1:XSIZE,1:YSIZE) = reshape((/ (i*i,i=1,XSIZE) /),shape(PHIOLD))
END PROGRAM LAPLACE
