PROGRAM LAPLACE
    INTEGER, PARAMETER :: XSIZE=101,YSIZE=101
    REAL(8), DIMENSION(1:XSIZE,1:YSIZE) :: PHIOLD,PHINEW
    REAL :: MAXDELTA

    REAL, PARAMETER :: CONVERGENCE = 0.000001
    INTEGER :: ITERATIONS = 0

    INTEGER :: I,J

    DO I=1,XSIZE
        DO J=1,YSIZE
            PHINEW(I,J) = I*I-J*J
        END DO
    END DO
    
    PHINEW(2:XSIZE-1,2:YSIZE-1)=0

    JACOBI_ITERATION: DO
        ITERATIONS = ITERATIONS+1
        PHIOLD=PHINEW

        PHINEW(2:XSIZE-1,2:YSIZE-1)=0.25*(&
            &PHIOLD(1:XSIZE-2,2:YSIZE-1)+&
            &PHIOLD(3:XSIZE,2:YSIZE-1)+&
            &PHIOLD(2:XSIZE-1,1:YSIZE-2)+&
            &PHIOLD(2:XSIZE-1,3:YSIZE))
        MAXDELTA = MAXVAL(ABS(PHINEW(2:XSIZE-1,2:YSIZE-1)-PHIOLD(2:XSIZE-1,2:YSIZE-1)))
        IF (MAXDELTA < CONVERGENCE) EXIT JACOBI_ITERATION

     END DO JACOBI_ITERATION
   
    print *, ITERATIONS,' ITERATIONS'
    print *, ' FINAL RESULT = '
    DO I=1,XSIZE
        DO J=1,YSIZE
            print *,'PHI(',I,',',J,') = ',PHINEW(I,J)
        END DO
    END DO
END PROGRAM LAPLACE
