PROGRAM LAPLACE
    INTEGER, PARAMETER :: XSIZE=101,YSIZE=101
    REAL(8), DIMENSION(1:XSIZE,1:YSIZE) :: PHIOLD,PHINEW,ERROR
    REAL :: MAXDELTA
    REAL(8) :: ERRORSUM,NSQ=XSIZE*YSIZE

    REAL(8), PARAMETER :: CONVERGENCE = EPSILON(ERRORSUM)
    INTEGER :: ITERATIONS = 0

    INTEGER :: I,J

    DO I=1,XSIZE
        DO J=1,YSIZE
            PHINEW(I,J) = (I*I-J*J)/(NSQ)
        END DO
    END DO
    
    PHINEW(2:XSIZE-1,2:YSIZE-1)=0

    open(10,file='jacobi_101.csv')

    JACOBI_ITERATION: DO
        ITERATIONS = ITERATIONS+1
        PHIOLD=PHINEW

        PHINEW(2:XSIZE-1,2:YSIZE-1)=0.25*(&
            &PHIOLD(1:XSIZE-2,2:YSIZE-1)+&
            &PHIOLD(3:XSIZE,2:YSIZE-1)+&
            &PHIOLD(2:XSIZE-1,1:YSIZE-2)+&
            &PHIOLD(2:XSIZE-1,3:YSIZE))
        ERROR = PHIOLD-PHINEW
        ERRORSUM = SQRT(SUM(ERROR*ERROR)/NSQ)
        write(10,*) ERRORSUM, ITERATIONS 
        IF (ERRORSUM < 2*CONVERGENCE) EXIT JACOBI_ITERATION

     END DO JACOBI_ITERATION
   
    close(10)
END PROGRAM LAPLACE
